/**
 * GET /api/scans/[id]/report?format=markdown — bug-bounty / pentest-report
 * shaped markdown of the scan, ready to paste into a HackerOne / Bugcrowd /
 * internal ticket.
 *
 * Format flavors:
 *   - markdown (default)
 *   - exec-summary (one-pager for non-technical audience)
 */

import { NextResponse } from "next/server";
import { getScan, listFindings } from "@/lib/store";
import { rankFindings } from "@/lib/triage/ranker";
import type { Finding } from "@/lib/types";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const SEV_ICON: Record<string, string> = {
  critical: "🔴", high: "🟠", medium: "🟡", low: "🔵", info: "⚪",
};

function fmtMarkdown(scan: { id: string; target: { value: string }; createdAt: number; counts: Record<string, number> }, findings: Finding[]): string {
  const ranked = rankFindings(findings);
  const total = findings.length;
  const counts = scan.counts;
  const lines: string[] = [];

  lines.push(`# Security Assessment Report — \`${scan.target.value}\``);
  lines.push("");
  lines.push(`**Scan id**: \`${scan.id}\``);
  lines.push(`**Date**: ${new Date(scan.createdAt).toISOString()}`);
  lines.push(`**Total findings**: ${total}`);
  lines.push("");
  lines.push("## Severity breakdown");
  lines.push("");
  lines.push("| Severity | Count |");
  lines.push("|----------|-------|");
  for (const s of ["critical", "high", "medium", "low", "info"]) {
    lines.push(`| ${SEV_ICON[s]} ${s} | ${counts[s] ?? 0} |`);
  }
  lines.push("");
  lines.push("## Top 10 by ROI");
  lines.push("");
  for (const r of ranked.slice(0, 10)) {
    const f = r.finding;
    lines.push(`### ${r.rank}. ${SEV_ICON[f.severity]} ${f.title}`);
    lines.push("");
    lines.push(`- **Score**: ${Math.round(r.score)} (${r.reason})`);
    lines.push(`- **Rule**: \`${f.ruleId ?? "unknown"}\``);
    if (f.cwe?.length) lines.push(`- **CWE**: ${f.cwe.join(", ")}`);
    if (f.cve?.length) lines.push(`- **CVE**: ${f.cve.join(", ")}`);
    if (f.owasp?.length) lines.push(`- **OWASP**: ${f.owasp.join(", ")}`);
    lines.push(`- **Location**: \`${f.location.url ?? f.location.file ?? "?"}\``);
    if (f.confidence) lines.push(`- **Confidence**: ${f.confidence}`);
    lines.push("");
    lines.push("**Description**");
    lines.push("");
    lines.push(f.description.split("\n").join("  \n"));
    lines.push("");
    if (f.remediation) {
      lines.push("**Remediation**");
      lines.push("");
      lines.push(f.remediation);
      lines.push("");
    }
    if (f.references?.length) {
      lines.push("**References**");
      for (const ref of f.references) lines.push(`- ${ref}`);
      lines.push("");
    }
  }
  lines.push("---");
  lines.push("");
  lines.push(`Generated by moba-scanner. Reproduce: \`GET /api/scans/${scan.id}\`.`);
  return lines.join("\n");
}

function fmtExecSummary(scan: { id: string; target: { value: string }; counts: Record<string, number> }, findings: Finding[]): string {
  const c = scan.counts;
  const total = findings.length;
  const tier1 = c.critical + c.high;
  return `# ${scan.target.value} — Security Posture One-Pager

**Total findings:** ${total}  ·  **Action required:** ${tier1}

🔴 Critical: ${c.critical ?? 0}  ·  🟠 High: ${c.high ?? 0}  ·  🟡 Medium: ${c.medium ?? 0}  ·  🔵 Low: ${c.low ?? 0}  ·  ⚪ Info: ${c.info ?? 0}

${tier1 > 0 ? `**The ${tier1} critical / high findings should be remediated this week.** See full report for details.` : "**No critical or high findings.** Maintain current posture; investigate medium-severity items as part of normal hygiene."}

Top categories observed:
${Object.entries(findings.reduce<Record<string, number>>((acc, f) => { acc[f.scannerName] = (acc[f.scannerName] ?? 0) + 1; return acc; }, {})).sort((a, b) => b[1] - a[1]).slice(0, 5).map(([s, n]) => `- ${s}: ${n}`).join("\n")}

Reproduce: scan id \`${scan.id}\`.`;
}

export async function GET(req: Request, ctx: RouteContext<"/api/scans/[id]/report">) {
  const { id } = await ctx.params;
  const url = new URL(req.url);
  const format = url.searchParams.get("format") ?? "markdown";
  const scan = await getScan(id);
  if (!scan) return NextResponse.json({ error: "not found" }, { status: 404 });
  const findings = await listFindings(id);
  const md = format === "exec-summary" ? fmtExecSummary(scan, findings) : fmtMarkdown(scan, findings);
  return new NextResponse(md, {
    headers: {
      "Content-Type": "text/markdown; charset=utf-8",
      "Content-Disposition": `attachment; filename="moba-${id}.md"`,
    },
  });
}
