/**
 * Encrypted target vault — store sensitive scan config (auth headers,
 * bearer tokens, login profiles, API keys for VirusTotal/Shodan/MobSF/etc.)
 * encrypted at rest with AES-256-GCM.
 *
 * Key derivation:
 *   - The master key comes from `MOBA_VAULT_KEY` env var.
 *   - If unset, we error rather than use a default — silent insecure storage
 *     is worse than a hard fail.
 *   - Per-record nonce, integrity tag.
 *
 * Storage: data/vault.json — encrypted blobs only, no plaintext leakage.
 *
 * Usage:
 *   await vault.put("github-token", "ghp_xxxxxxxxxxxx")
 *   const token = await vault.get("github-token")
 *   await vault.delete("github-token")
 *
 * IMPORTANT: this is a basic envelope. For real-world deployments use a
 * proper KMS — but for a self-hosted scanner this is far better than
 * storing tokens in `.env`-shaped plaintext.
 */

import { promises as fs, existsSync, readFileSync, writeFileSync, chmodSync, mkdirSync } from "node:fs";
import path from "node:path";
import { createCipheriv, createDecipheriv, randomBytes, scryptSync } from "node:crypto";

const FILE = path.join(process.cwd(), "data", "vault.json");
const KEY_FILE = path.join(process.cwd(), "data", "vault.key");
const ALGO = "aes-256-gcm";
const KEY_LEN = 32;
const IV_LEN = 12;
const TAG_LEN = 16;

interface VaultRecord {
  key: string;
  iv: string;
  tag: string;
  ct: string;
  createdAt: number;
}

/**
 * Resolve the master secret for the vault, in priority order:
 *   1. `MOBA_VAULT_KEY` env var (deployment override).
 *   2. `data/vault.key` on disk (self-hosted default).
 *   3. None of the above → generate a random secret, write it to
 *      `data/vault.key` with 0o600 perms, and use that going forward.
 *
 * Step 3 is what makes the UI self-serve: a user can install the app and
 * capture their first login profile without having to set env vars by hand.
 * The downside (a file on the host containing the key) matches Node's own
 * trust boundary — anyone with read on the process directory could already
 * read `vault.json` and live state anyway.
 */
function resolveMasterSecret(): { raw: string; autoGenerated: boolean } {
  const env = process.env.MOBA_VAULT_KEY;
  if (env) return { raw: env, autoGenerated: false };
  try {
    const onDisk = readFileSync(KEY_FILE, "utf8").trim();
    if (onDisk) return { raw: onDisk, autoGenerated: false };
  } catch {
    /* missing — fall through to generation */
  }
  // Generate, persist, return. Synchronous so the very first vaultPut after
  // a fresh install doesn't have to await anything special.
  const fresh = randomBytes(32).toString("hex");
  try {
    mkdirSync(path.dirname(KEY_FILE), { recursive: true });
    writeFileSync(KEY_FILE, fresh + "\n", { encoding: "utf8", flag: "wx" });
    try { chmodSync(KEY_FILE, 0o600); } catch { /* Windows ignores POSIX perms */ }
  } catch (e) {
    // Race: another worker just wrote it. Re-read and use that one so we all
    // agree on the same key.
    if ((e as NodeJS.ErrnoException).code === "EEXIST") {
      return { raw: readFileSync(KEY_FILE, "utf8").trim(), autoGenerated: false };
    }
    throw e;
  }
  // eslint-disable-next-line no-console
  console.warn(`[vault] generated new master key at ${KEY_FILE}. Back this file up.`);
  return { raw: fresh, autoGenerated: true };
}

/** True iff the vault has a usable key (env or file present). Used by the
 *  setup-status endpoint so the UI can show ✓ before any write. */
export function vaultKeyConfigured(): boolean {
  if (process.env.MOBA_VAULT_KEY) return true;
  return existsSync(KEY_FILE);
}

/** Force the master secret to materialize (generates `data/vault.key` if it
 *  doesn't exist yet). Idempotent. The setup-status endpoint calls this so
 *  the UI checklist flips to green immediately without waiting for a real
 *  vault write to trigger the auto-generation lazily. */
export function ensureVaultKey(): void {
  // Trigger resolution + cache. We don't need the buffer here — the side
  // effect of writing data/vault.key when missing is the whole point.
  getKey();
}

let cachedKey: Buffer | null = null;
function getKey(): Buffer {
  if (cachedKey) return cachedKey;
  const { raw } = resolveMasterSecret();
  // Derive a stable 32-byte key from the secret via scrypt.
  cachedKey = scryptSync(raw, "moba-scanner-vault-v1", KEY_LEN);
  return cachedKey;
}

async function load(): Promise<VaultRecord[]> {
  try { return JSON.parse(await fs.readFile(FILE, "utf8")); } catch { return []; }
}
async function save(items: VaultRecord[]) {
  await fs.mkdir(path.dirname(FILE), { recursive: true });
  await fs.writeFile(FILE, JSON.stringify(items, null, 2), "utf8");
}

export async function vaultPut(key: string, value: string): Promise<void> {
  const k = getKey();
  const iv = randomBytes(IV_LEN);
  const cipher = createCipheriv(ALGO, k, iv);
  const ct = Buffer.concat([cipher.update(value, "utf8"), cipher.final()]);
  const tag = cipher.getAuthTag();
  const items = (await load()).filter((r) => r.key !== key);
  items.push({ key, iv: iv.toString("base64"), tag: tag.toString("base64"), ct: ct.toString("base64"), createdAt: Date.now() });
  await save(items);
}

export async function vaultGet(key: string): Promise<string | null> {
  const k = getKey();
  const items = await load();
  const r = items.find((x) => x.key === key);
  if (!r) return null;
  const iv = Buffer.from(r.iv, "base64");
  const tag = Buffer.from(r.tag, "base64");
  const ct = Buffer.from(r.ct, "base64");
  const decipher = createDecipheriv(ALGO, k, iv);
  decipher.setAuthTag(tag);
  try {
    const pt = Buffer.concat([decipher.update(ct), decipher.final()]);
    return pt.toString("utf8");
  } catch { return null; }
}

export async function vaultDelete(key: string): Promise<void> {
  const items = (await load()).filter((r) => r.key !== key);
  await save(items);
}

export async function vaultList(): Promise<string[]> {
  return (await load()).map((r) => r.key);
}
