/**
 * GET /api/scans/[id]/compliance/[framework]/html
 *
 * Returns a printable HTML compliance report (Ctrl+P → Save as PDF works in
 * any browser; no puppeteer dep required). Uses inline CSS so it renders
 * correctly even when saved offline.
 */

import { NextResponse } from "next/server";
import { listFindings, getScan } from "@/lib/store";
import { buildReport, type Framework } from "@/lib/compliance/mapping";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const VALID: Framework[] = ["PCI-DSS", "SOC2", "HIPAA", "ISO27001"];

function escape(s: string): string {
  return String(s).replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "\"": "&quot;", "'": "&#39;" } as const)[c]!);
}

const SEV_COLOR: Record<string, string> = {
  critical: "#b3261e", high: "#ff8800", medium: "#ffcc00", low: "#4477aa", info: "#888",
};

export async function GET(_req: Request, ctx: RouteContext<"/api/scans/[id]/compliance/[framework]/html">) {
  const { id, framework } = await ctx.params;
  if (!VALID.includes(framework as Framework)) return NextResponse.json({ error: "bad framework" }, { status: 400 });
  const scan = await getScan(id);
  if (!scan) return NextResponse.json({ error: "not found" }, { status: 404 });
  const findings = await listFindings(id);
  const r = buildReport(framework as Framework, findings);
  const date = new Date(scan.createdAt).toISOString().slice(0, 10);

  const html = `<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<title>${escape(framework)} Compliance Report — ${escape(scan.target.value)}</title>
<style>
  *,*::before,*::after { box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", system-ui, sans-serif; max-width: 920px; margin: 2em auto; padding: 0 2em; color: #1a1a1a; line-height: 1.5; }
  h1 { margin-bottom: 0.2em; }
  h2 { margin-top: 2em; border-bottom: 2px solid #e5e7eb; padding-bottom: 0.2em; }
  .meta { color: #6b7280; margin-bottom: 2em; font-size: 0.95em; }
  .summary { display: grid; grid-template-columns: repeat(5, 1fr); gap: 1em; margin: 1.5em 0; }
  .summary > div { padding: 1em; border-radius: 8px; border: 1px solid #e5e7eb; text-align: center; }
  .summary strong { font-size: 1.6em; display: block; }
  table { width: 100%; border-collapse: collapse; margin: 1em 0; }
  th, td { padding: 0.6em 0.8em; border-bottom: 1px solid #e5e7eb; text-align: left; vertical-align: top; }
  th { background: #f9fafb; font-weight: 600; }
  .ctrl { font-family: ui-monospace, monospace; white-space: nowrap; }
  .sev { display: inline-block; padding: 0.1em 0.5em; border-radius: 0.5em; color: #fff; font-size: 0.8em; margin-right: 0.3em; }
  .uncovered { background: #f0fdf4; padding: 1em; border-radius: 6px; border: 1px solid #bbf7d0; color: #166534; margin-bottom: 1em; }
  footer { margin-top: 3em; color: #6b7280; font-size: 0.85em; border-top: 1px solid #e5e7eb; padding-top: 1em; }
  @media print { body { margin: 1em; } h2 { page-break-before: avoid; } }
</style></head><body>
<h1>${escape(framework)} Compliance Report</h1>
<p class="meta">Target: <code>${escape(scan.target.value)}</code> · Scan ${escape(scan.id)} · Generated ${date}</p>

<h2>Severity summary</h2>
<div class="summary">
  ${(["critical","high","medium","low","info"] as const).map((s) => `<div><strong style="color:${SEV_COLOR[s]}">${scan.counts[s] ?? 0}</strong>${s.toUpperCase()}</div>`).join("")}
</div>

<h2>Controls covered (${r.controls.length})</h2>
<table>
  <thead><tr><th>Control</th><th>Description</th><th>Findings</th><th>Severity</th></tr></thead>
  <tbody>
  ${r.controls.map((c) => `<tr>
    <td class="ctrl"><strong>${escape(c.control)}</strong></td>
    <td>${escape(c.description)}</td>
    <td>${c.findings}</td>
    <td>${Object.entries(c.severityCounts).map(([s, n]) => `<span class="sev" style="background:${SEV_COLOR[s]}">${s}: ${n}</span>`).join("")}</td>
  </tr>`).join("")}
  </tbody>
</table>

<h2>Controls with no findings (${r.uncoveredControls.length})</h2>
${r.uncoveredControls.length === 0 ? "<p>(every tracked control had at least one finding)</p>" : `<div class="uncovered">${r.uncoveredControls.map((c) => `<code class="ctrl">${escape(c)}</code>`).join(", ")}</div><p style="color:#6b7280">No findings observed against these controls. Either the application is compliant on these axes, OR no scanner currently tests for them — confirm via test plan.</p>`}

<h2>Sample findings (top per control)</h2>
${r.controls.flatMap((c) => c.sampleFindings.slice(0, 3).map((f) => `<p><span class="sev" style="background:${SEV_COLOR[f.severity]}">${f.severity}</span> <strong>${escape(c.control)}</strong> — ${escape(f.title)}</p>`)).join("")}

<footer>
  Generated by <strong>moba-scanner</strong>. Mappings reflect CWE / OWASP-Top-10 → ${escape(framework)} controls. This report is an automated artifact and does NOT replace a formal audit.
</footer>
</body></html>`;
  return new NextResponse(html, { headers: { "Content-Type": "text/html; charset=utf-8" } });
}
